-- ADD CHECK INTO A COLUMNS 
ALTER TABLE employees
ADD CONSTRAINT chk_hourly_pay CHECK(hourly_pay>=15.00); 


-- THIS WILL GIVE ERROR AS THE HOURLY PAY IS LESS THAN WHAT WE HAVE DEFINED
INSERT INTO EMPLOYEES
VALUE(8,"Sheldon","Plankton",7.00,"2023-01-29"); 