-- PRIMARY KEY IS ASSIGNED WHEN A COLUMN NEED TO BE UNIQUE AND NOT NULL
-- A TABLE WILL HAVE ONLY ONE PRIMARY KEY CONTRAINTS

-- CREATE A TABLE WITH PRIMARY KEY
CREATE TABLE transactions (
transaction_id INT PRIMARY KEY,
amount DECIMAL(5,2)
);

-- ADD PRIMARY KEY TO AN EXISITING TABLE
ALTER TABLE transactions
ADD CONSTRAINT 
PRIMARY KEY (transaction_id)