-- SELECT ALL FROM EMPLOYEES;
SELECT * FROM employees;

-- SELECT SPECIFIC COLUMN FROM THE TABLE
SELECT first_name FROM employees;

-- SELECT SPECIFIC COLUMNS FROM THE TABLE
SELECT first_name,last_name FROM employees;

-- SELECT EMPLOYEE WITH A SPECIFIC ID
SELECT * FROM employees
WHERE employee_id =1;


-- SELECT EMPLOYEE WITH A SPECIFIC NAME
SELECT * FROM employees
WHERE first_name ="Eugine";

-- SELECT EMPLOYEE WHOSE HOURLY PAY IS LESS THAN 25
SELECT * FROM employees
WHERE hourly_pay<25;

-- SELECT EMPLOYEES WHOSE JOINING DATE IS LESS THAN EQUAL TO 27 JAN 2023
SELECT * FROM employees
WHERE hire_date <= "2023-01-27";

-- SELECT ALL EMPLOYEE WHOSE ID IS NOT EQUAL TO 1
SELECT * FROM employees
WHERE employee_id != 1;