-- LETS FIRST CREATE A TABLE WHICH WHILL HAVE A PRIMARY KEY 
CREATE TABLE CUSTOMERS(
	CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255)
);

-- INSERTING SOME DATA INTO CUSTOMERS TABLE
INSERT INTO CUSTOMERS(FIRST_NAME,LAST_NAME)
VALUES 
('LARRY','SMITCH'),
('KILEN','JAMES'),
('HAROLD','GOMES'),
('PANTON','MICHEALS');


-- NOW CREATING A TABLE WITH A FORIGN KEY LINKED TO THE PRIMARY KEY OF THE PREVIOUS TABLE
CREATE TABLE TRANSACTIONS(
TRANSACTION_ID INT PRIMARY KEY AUTO_INCREMENT,
AMOUNT DECIMAL(5,2),
CUSTOMER_ID INT,
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);


 

-- DELETE FORIGN KEY FROM TABLE
ALTER TABLE transactions
DROP FOREIGN KEY transactions_ibfk_1;  -- this unique foreign key name could be found under table column foreign key

