-- JOINS ARE BASICALLY USED TO COMBINE TABLES FROM TWO OR MORE TABLE BASED ON RELATED COLUMN BETWEEN THEM



-- CREATE INNER JOIN WITH CUSTOMER_ID FROM TABLE TRANSACTIONS AND CUSTOMERS

SELECT *
FROM TRANSACTIONS INNER JOIN CUSTOMERS
ON TRANSACTIONS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;

-- GET ONLY TRANSACTION ID, AMOUNT, fName  AND lName  using INNER JOIN
SELECT 
transaction_id, amount, first_name, last_name
FROM
transactions INNER JOIN customers
ON transactions.customer_id = customers.customer_id;



-- GET ALL THE DATAS FROM THE LEFT TABLE AND ONLY MATCHED DATA FROM THE RIGHT TABLE
SELECT *
FROM TRANSACTIONS LEFT JOIN CUSTOMERS
ON TRANSACTIONS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;


-- GET ALL THE DATAS FROM THE RIGHT TABLE AND ONLY MATCHED DATA FROM THE RIGHT TABLE

SELECT *
FROM TRANSACTIONS RIGHT JOIN CUSTOMERS
ON TRANSACTIONS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;