-- MYSQL FUNCTIONS

-- COUNT FUNCTION WHICH IS USED TO COUNT A COLUMNS BASICALLY FROM A TABLE
SELECT COUNT(AMOUNT)
FROM TRANSACTIONS;


-- RENAME THE COUNT FUNCTION RESULT COLUMNS 
SELECT COUNT(AMOUNT) AS "TODAYS_TRANSACTION"
FROM TRANSACTIONS;
               -- where ; we can use where clause to filter data here as well


-- FIND MAXIMUMM VALUE IN A COLUMN
SELECT MAX(AMOUNT) AS "Max_Purchase"
FROM TRANSACTIONS;


-- FIND MINIMUM VALUE IN COLUMN
SELECT MIN(AMOUNT) AS "MINIMUM_Purchase"
FROM TRANSACTIONS;


-- FIND AVERAGE VALUE FROM A COLUMN
SELECT AVG(AMOUNT) AS "Average_Purchase"
FROM TRANSACTIONS;


-- FIND SUM OF ALL VALUE IN A COLUMN
SELECT SUM(AMOUNT) AS "TOTAL_PURCHASE"
FROM TRANSACTIONS;


-- CONCAT DATA FROM TWO COLUMNS AND GET 
SELECT CONCAT(FIRST_NAME," ",LAST_NAME ) AS "FULL NAME"
FROM CUSTOMERS;