-- ORDER NAME IN THE TABLE IN ASSENDING ORDER
SELECT * FROM EMPLOYEE
ORDER BY Emp_Name ;	

-- ORDER NAME IN THE TABLE IN DESCENDING ORDER
SELECT * FROM EMPLOYEE
ORDER BY  Emp_Name DESC ;	


-- ORDER AMOUNT IN TRANSACTIONS IN ASECENDING WHEN TWO AMOUNT IS SIMILAR THEN ORDER IT BY CUSTOMER_ID
SELECT * FROM transactions
ORDER BY AMOUNT,CUSTOMER_ID ASC;


