-- GET ONLY 2 DATA FROM TABLE FROM STARTING
SELECT * FROM customers
LIMIT 2; -- LIMIT VALUE


-- GET ONLY 3 DATA FROM TABLE ORDER BY DESCENDING FIRSTNAME
SELECT * FROM customers
ORDER BY FIRST_NAME DESC LIMIT 3;

-- GET ONLY 3rd Data from Table
SELECT * FROM customers
LIMIT 2,1;  -- LIMIT INDEX,VALUE