-- CREATE SIMPLE TABLE INSIDE DATABASE
--- FIRST CREATE A DABASE AND SELECT/USE THAT DATABASE


---- CREATE A SIMPLE TABLE WITH FIELDS
create table employee(
employee_id INT,
first_name VARCHAR(50),
last_Name VARCHAR(50),
hourly_pay DECIMAL(5,2),
hire_date DATE
);


-- SELECT TABLE FROM DATABASE <- This will show the complete table datas
SELECT * FROM EMPLOYEE;

-- RENAME TABLE 
RENAME TABLE employee TO employees;

-- DROP TABLE 
DROP TABLE employees;


-- ADD A NEW COLUMN IN THE TABLE
ALTER TABLE employees
ADD phone_number VARCHAR(15);

-- RENAME COLUMN NAME IN THE TABLE
ALTER TABLE employees
RENAME COLUMN phone_number TO email;


-- CHANGE DATATYPE OF A COLUMN
ALTER TABLE employees
MODIFY COLUMN email VARCHAR(100);


-- CHANGE POSITION OF EMAIL COLUMN TO BE AFTER THE LAST NAME
ALTER TABLE employees
MODIFY email VARCHAR(100)
AFTER last_Name;


-- CHANGE POSITION OF EMAIL TO BE AT THE BEGINING OF THE TABLE
ALTER TABLE employees
MODIFY email VARCHAR(100)
FIRST;


-- DROP COLUMN 
ALTER TABLE employees
DROP COLUMN email; 